### ISSUE TITLE
URIError: Unable to parse 'address' to 'URL' class.

### ISSUE THREAD

**Issue by gvmii** [SpacingBat3/discord-ipc-proxy#1]
```
PS D:\Usuario\Documents\Programming\Misc stuff\discord-ipc-proxy> npm start

> discord-ipc-proxy@1.0.0-rc1 start
> tsc && node dist/index.js

{"evt":"listening","transport":"ws","receiver":"both","port":6463,"timestamp":[886,493887800]}
D:\Ixogamer\Documents\Programming\Misc stuff\discord-ipc-proxy\dist\index.js:41
            throw new URIError("Unable to parse 'address' to 'URL' class.");
                  ^

URIError: Unable to parse 'address' to 'URL' class.
    at D:\Ixogamer\Documents\Programming\Misc stuff\discord-ipc-proxy\dist\index.js:41:19
    at getServer (D:\Ixogamer\Documents\Programming\Misc stuff\discord-ipc-proxy\dist\index.js:43:7)
    at D:\Ixogamer\Documents\Programming\Misc stuff\discord-ipc-proxy\dist\index.js:67:24
    at new Promise (<anonymous>)
    at D:\Ixogamer\Documents\Programming\Misc stuff\discord-ipc-proxy\dist\index.js:66:27
    at tryUntil (D:\Ixogamer\Documents\Programming\Misc stuff\discord-ipc-proxy\dist\index.js:20:23)
    at tryUntil (D:\Ixogamer\Documents\Programming\Misc stuff\discord-ipc-proxy\dist\index.js:24:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async tryUntil (D:\Ixogamer\Documents\Programming\Misc stuff\discord-ipc-proxy\dist\index.js:24:20)
    at async tryUntil (D:\Ixogamer\Documents\Programming\Misc stuff\discord-ipc-proxy\dist\index.js:24:20)

Node.js v18.17.0
PS D:\Usuario\Documents\Programming\Misc stuff\discord-ipc-proxy>
```

**Comment by SpacingBat3** [comment]
Oh, I think it might be because of duplicate `:` in path in case of Windows (because of drive letter), I guess I might try to encode it to Unix-alike path, with `/a/` meaning an `A:` drive, so it will work properly when placed in `URL` class.

I have to admit, I haven't tested how this kind of proxy works on Windows.
